name: My First Workflow
on: 
  push:
    branches:
      - main
jobs:
  myFirstJobs:
    runs-on: ubuntu-latest
    steps:
      - name: My First Step
        run: printenv
      - name: My Second Step
        run: |
          echo "Hello World!"
          echo "Bye" > file.txt
          ls
          cat file.txt
      - name: Sleep step
        run: sleep 5
